### ISSUE TITLE
REST: restarting a model, that has not run yet, results in an exception

### ISSUE THREAD

**Issue by uvexgmessow** [GraphWalker/graphwalker-project#200] opened 2019-01-24 08:24 UTC
If you start graphwalker with "online -s RESTFUL" and send "restart" as first command, then an IndexOutOfBoundsException is thrown.
The bug is in line 197 of Restful.java, where it's assumed that the executionPath in SimpleProfiler contains an element at index 0. However it's empty at this point in time.

**Comment by nilols** [comment] 2019-01-24 08:47
Sounds like it could be a easy fix, do you wanna do a PR? =)

**Comment by uvexgmessow** [comment] 2019-01-24 09:17
I don't have a java dev environment, but I'll see what I can do.

**Comment by uvexgmessow** [comment] 2019-01-24 10:20
I'm sorry, I can't get the intellij community edition to run properly, there are always weird error messages about symbols that cannot be resolved. I'm not a java developer, so I unfortunately don't have the time to get this set up and running. I only used PhpStorm so far and it never had strange issues like that, it simply does index everything and then it works.

**Comment by nilols** [comment] 2019-01-24 11:34
I'm glad that you tried.

The symbol issue is due to that you need to configure the jdk for the project in intellij, there is a button in the top right corner where you can do this 
![image](https://user-images.githubusercontent.com/1027531/51675369-caa6cb80-1fd3-11e9-9d21-0be1933cc3bf.png)
and you need to have jdk 1.8 on your machine (not sure if there is a bundled jdk with that version) but I'll have a look at this issue so don't worry

**Comment by nilols** [comment] 2019-01-24 22:38
@uvexgmessow The PR #201  will not change any behaviour, the service will still respond with a `nok` value, but the PR will remove the ugly stacktrace from the output.

@KristianKarl (@toredal) can you have a look at the PR and see if there is a reason why `printStackTrace()` is used, debug purpose?

**Comment by nilols** [comment] 2019-01-26 09:37
I think this issue got close by the merge, due to that they were linked

**Comment by toredal** [comment] 2019-01-26 09:49
I updated the binaries linked on http://graphwalker.github.io/download/

Latest CLI:  `4.0.0-SNAPSHOT-f95d1cf`
Latest Studio: `4.0.0-SNAPSHOT-f95d1cf`

(Use `--version` argument to get your version)

**Comment by Robert-96** [comment] 2019-01-26 21:48
Why is the service still responding with a `nok` value? Is this the expected behavior?

I expect when calling `restart` to reset the current path, and if the path is empty it should do nothing like calling `clear` on an empty list.

And if this is the expected behavior I think that a better error message should be returned. 

```
{
  "result": "nok",
  "error": "Index: 0, Size: 0"
}
```

It's not very helpful. `Index: 0, Size: 0` doesn't help you if you did not see the code.

**Comment by toredal** [comment] 2019-01-28 09:35
Hmm, yeah. You definitely got a point.
Our `reset` should be stateless, and in this case just work, and return `ok`.
I'll look into that today.

**Comment by toredal** [comment] 2019-01-28 13:02
The PR #202 is proposed fix.
@nilols I added an understandable (for an end user) error string for the case of trying a `restart` when no models are loaded - `resetEmptyMachine`.
And for the case `resetNotYetStartedMachine` I the reset will happen, even though no profile path exists.

BTW, I really like your added simple unit test for the rest service!

**Comment by toredal** [comment] 2019-01-29 09:12
> Hmm, yeah. You definitely got a point.
> Our `reset` should be stateless, and in this case just work, and return `ok`.
> I'll look into that today.

A clarification. The `reset` command is not stateless. If no models are loaded, a reset is not really meaningful.

**Comment by toredal** [comment] 2019-01-30 15:08
@Robert-96 The fix is merged, and a new binary is now available `graphwalker-cli-4.0.0-SNAPSHOT.jar` at http://graphwalker.github.io/download/

Fixed by https://github.com/GraphWalker/graphwalker-project/pull/202

**Closed by toredal** 2019-01-30 15:08 UTC
